---
- hosts: Servers
  sudo: yes
  tasks:
    - name: stop nginx
      service:
       name: nginx
       state: stopped

    - name: uninstall nginx
      yum:
       name: nginx 
       state: absent
